Naming: error vs uncertainty
resultwizard/ResultWizard pull request #43
Opened 2024-04-11 21:45 UTC by paul019

2024-04-11 21:45 UTC, paul019 commented
Fixes #38

2024-04-11 21:59 UTC, Splines commented on src/api/console_stringifier.py
Did you intend to have this in this PR?

2024-04-11 22:00 UTC, paul019 commented on src/api/console_stringifier.py
No

2024-04-11 23:42 UTC, Splines commented
I converted this PR to a draft. Please open it once the pipeline is passing and once this PR is ready for my review.

2024-04-12 15:53 UTC, Splines requested changes
Could you also rename `error_name_prefix` and `error_name_suffix`?
(`Ctrl + Shift + F` in VSCode)

2024-04-24 15:53 UTC, Splines approved these changes

2024-04-27 18:25 UTC, merged